// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjoeX0LEX8VLRcahpD6OLKix6N64VxZuE',
    appId: '1:779825517895:web:1b5d1799ebf3e49f0de862',
    messagingSenderId: '779825517895',
    projectId: 'ada-project-e9318',
    authDomain: 'ada-project-e9318.firebaseapp.com',
    storageBucket: 'ada-project-e9318.appspot.com',
    measurementId: 'G-EQP1K4PG8J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9I2jThHqNkol-JQ0_eKsTBCCWeHfvmik',
    appId: '1:779825517895:android:ad8f33b42ff054590de862',
    messagingSenderId: '779825517895',
    projectId: 'ada-project-e9318',
    storageBucket: 'ada-project-e9318.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxTxnhyIF-WaSc_fk7OHyJCoE8Uxdr3N0',
    appId: '1:779825517895:ios:759be5334dbf46f80de862',
    messagingSenderId: '779825517895',
    projectId: 'ada-project-e9318',
    storageBucket: 'ada-project-e9318.appspot.com',
    iosClientId: '779825517895-jndqp061cjvqvv34t89su91gfff4jgec.apps.googleusercontent.com',
    iosBundleId: 'com.example.example',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAxTxnhyIF-WaSc_fk7OHyJCoE8Uxdr3N0',
    appId: '1:779825517895:ios:759be5334dbf46f80de862',
    messagingSenderId: '779825517895',
    projectId: 'ada-project-e9318',
    storageBucket: 'ada-project-e9318.appspot.com',
    iosClientId: '779825517895-jndqp061cjvqvv34t89su91gfff4jgec.apps.googleusercontent.com',
    iosBundleId: 'com.example.example',
  );
}
